env:
  global:
    - secure: "Q+SwRzZ0meFuwNj8DDctw6Wwk50/GhG9gQJQMyIcT0vdcVGeQlBSscQT9z2LHcezpS4hIgyosEqteOAtOmT78Lxaq0PVLX84lcym4WO8Bk7OQZ5jHddImCvygVAByZwEMC2MHyKkBkfsijAz0qvyyFIuPMbZ+I69jGppOtU/GB0="
    - LibSodiumVersion=1.0.3
os:
  - linux
  - osx
language: rust
rust:
  - nightly
#  - beta
#  - stable
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - $HOME/libsodium-$LibSodiumVersion
install:
  - curl -sSLO https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/install_libsodium.sh
  - . install_libsodium.sh
script:
  - cargo build --release --verbose --features "use-mock-routing"
  - cargo test --release --features "use-mock-routing"
after_success:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/deploy_gh-pages.sh | bash
