[package]
name          = "safe_core"
version       = "0.3.1"
authors       = ["MaidSafe Developers <dev@maidsafe.net>"]
description   = "SAFE Core API library"
documentation = "http://maidsafe.github.io/safe_core/latest/"
repository    = "https://github.com/maidsafe/safe_core"
readme        = "README.md"
license       = "GPL-3.0"
homepage      = "http://maidsafe.net"

[dependencies]
# ---- MaidSafe -----
routing            = "~0.4.2"
lru_time_cache     = "~0.2.5"
self_encryption    = "~0.2.5"
maidsafe_utilities = "~0.1.5"

# ---- Others ----
log             = "~0.3.4"
cbor            = "~0.3.16"
rand            = "~0.3.12"
sodiumoxide     = "~0.0.9"
rustc-serialize = "~0.3.16"

[dev-dependencies]
env_logger = "~0.3.2"

[features]
use-mock-routing = []
