[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Core API library"
documentation = "http://maidsafe.github.io/safe_core/latest/"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_core"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_core"
version = "0.8.0"

[dependencies]
log = "~0.3.5"
lru_time_cache = "~0.2.6"
maidsafe_utilities = "~0.3.0"
mpid_messaging = "~0.1.0"
rand = "~0.3.14"
routing = "~0.10.0"
rustc-serialize = "~0.3.18"
self_encryption = "~0.2.6"
sodiumoxide = "~0.0.9"
time = "~0.1.34"
xor_name = "~0.0.4"

[dependencies.clippy]
optional = true
version = "~0.0.44"

[dev-dependencies]
regex = "~0.1.55"

[[example]]
bench = false
name = "self_authentication"
test = true

[[example]]
bench = false
name = "safe_client"
test = false

[[example]]
bench = false
name = "rest_api"
test = true

[[example]]
bench = false
name = "simulate_browser"
test = true

[features]
use-mock-routing = []
